image: atlassian/pipelines-awscli

pipelines:
  default:
    - parallel:
        - step:
            name: Create .env and Build
            script:
              - echo "MONGO_SERVER=mongodb://localhost:27017/?retryWrites=true&w=majority" > .env
              - echo "PORT=8080" >> .env
              - IMAGE_NAME=$IMAGE_NAME
              - docker build -t $IMAGE_NAME:$BITBUCKET_BUILD_NUMBER -t $IMAGE_NAME .
              - pipe: atlassian/aws-ecr-push-image:2.2.0
                variables:
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  IMAGE_NAME: $IMAGE_NAME
                  TAGS: '$BITBUCKET_BUILD_NUMBER latest'
            services:
              - docker
