version: 0.2
    
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
     - npm install -g npm@10.3.0
     - npm install -g @nestjs/cli
     - npm install --legacy-peer-deps
  build:
    commands:
      -  npm run  build
  post_build:
    commands:
      - cp -R node_modules/ dist/node_modules
      - cp Procfile dist/Procfile


artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist