version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
